const dataListProvincial = [
    {
        "name": "Miền Bắc",
        "code": "MB",
        "area_id": 1,
        "weekdays": ",1,2,3,4,5,6,7,", 
    },
    {
        "name": "ĐắK Nông",
        "code": "XSDacNong",
        "area_id": 2,
        "weekdays": ",7,", 
    },
    {
        "name": "Đắc Lắc",
        "code": "XSDakLak",
        "area_id": 2,
        "weekdays": ",3,", 
    },
    {
        "name": "Gia Lai",
        "code": "XSGiaLai",
        "area_id": 2,
        "weekdays": ",6,", 
    },
    {
        "name": "Huế",
        "code": "XSTTH",
        "area_id": 2,
        "weekdays": ",2,", 
    },
    {
        "name": "Khánh Hòa",
        "code": "XSKhanhHoa",
        "area_id": 2,
        "weekdays": ",1,4,", 
    },
    {
        "name": "Kon Tum",
        "code": "XSKontum",
        "area_id": 2,
        "weekdays": ",1,", 
    },
    {
        "name": "Ninh Thuận",
        "code": "XSNinhThuan",
        "area_id": 2,
        "weekdays": ",6,", 
    },
    {
        "name": "Phú Yên",
        "code": "XSPhuYen",
        "area_id": 2,
        "weekdays": ",2,", 
    },
    {
        "name": "Quảng Bình",
        "code": "XSQuangBinh",
        "area_id": 2,
        "weekdays": ",5,", 
    },
    {
        "name": "Quảng Nam",
        "code": "XSQuangNam",
        "area_id": 2,
        "weekdays": ",3,", 
    },
    {
        "name": "Quảng Ngãi",
        "code": "XSQuangNgai",
        "area_id": 2,
        "weekdays": ",7,", 
    },
    {
        "name": "Quảng Trị",
        "code": "XSQuangTri",
        "area_id": 2,
        "weekdays": ",5,", 
    },
    {
        "name": "Đà Nẵng",
        "code": "XSDaNang",
        "area_id": 2,
        "weekdays": ",4,7,", 
    },
    {
        "name": "An Giang",
        "code": "XSAnGiang",
        "area_id": 3,
        "weekdays": ",5,", 
    },
    {
        "name": "Bà Rịa - Vũng Tàu",
        "code": "XSVungTau",
        "area_id": 3,
        "weekdays": ",3,", 
    },
    {
        "name": "Bạc Liêu",
        "code": "XSBacLieu",
        "area_id": 3,
        "weekdays": ",3,", 
    },
    {
        "name": "Bến Tre",
        "code": "XSBenTre",
        "area_id": 3,
        "weekdays": ",3,", 
    },
    {
        "name": "Bình Dương",
        "code": "XSBinhDuong",
        "area_id": 3,
        "weekdays": ",6,", 
    },
    {
        "name": "Bình Phước",
        "code": "XSBinhPhuoc",
        "area_id": 3,
        "weekdays": ",7,", 
    },
    {
        "name": "Bình Thuận",
        "code": "XSBinhThuan",
        "area_id": 3,
        "weekdays": ",5,", 
    },
    {
        "name": "Cà Mau",
        "code": "XSCaMau",
        "area_id": 3,
        "weekdays": ",2,", 
    },
    {
        "name": "Cần Thơ",
        "code": "XSCanTho",
        "area_id": 3,
        "weekdays": ",4,", 
    },
    {
        "name": "Hậu Giang",
        "code": "XSHauGiang",
        "area_id": 3,
        "weekdays": ",7,", 
    },
    {
        "name": "Kiên Giang",
        "code": "XSKienGiang",
        "area_id": 3,
        "weekdays": ",1,", 
    },
    {
        "name": "Long An",
        "code": "XSLongAn",
        "area_id": 3,
        "weekdays": ",7,", 
    },
    {
        "name": "Sóc Trăng",
        "code": "XSSocTrang",
        "area_id": 3,
        "weekdays": ",4,", 
    },
    {
        "name": "Tây Ninh",
        "code": "XSTayNinh",
        "area_id": 3,
        "weekdays": ",5,", 
    },
    {
        "name": "Tiền Giang",
        "code": "XSTienGiang",
        "area_id": 3,
        "weekdays": ",1,", 
    },
    {
        "name": "TP Hồ Chí Minh",
        "code": "XSTPHCM",
        "area_id": 3,
        "weekdays": ",2,7,", 
    },
    {
        "name": "Trà Vinh",
        "code": "XSTraVinh",
        "area_id": 3,
        "weekdays": ",6,", 
    },
    {
        "name": "Vĩnh Long",
        "code": "XSVinhLong",
        "area_id": 3,
        "weekdays": ",6,", 
    },
    {
        "name": "Đà Lạt",
        "code": "XSDaLat",
        "area_id": 3,
        "weekdays": ",1,", 
    },
    {
        "name": "Đồng Nai",
        "code": "XSDongNai",
        "area_id": 3,
        "weekdays": ",4,", 
    },
    {
        "name": "Đồng Tháp",
        "code": "XSDongThap",
        "area_id": 3,
        "weekdays": ",2,", 
    },
];
module.exports = dataListProvincial;